import { chromium } from "playwright";
const BASE = "http://localhost:3000";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1600, height: 920 }, deviceScaleFactor: 1.25 });
const page = await ctx.newPage();
page.on("pageerror", e => console.log("PAGEERR:", e.message.slice(0,150)));
await page.goto(`${BASE}/login`, { waitUntil: "networkidle" });
await page.fill("#email", "tariro@springfield.robocode.africa");
await page.fill("#password", "password123");
await page.click('button:has-text("Sign in")');
await page.waitForURL("**/app", { timeout: 15000 });
await page.goto(`${BASE}/app/projects`, { waitUntil: "networkidle" });
await page.waitForTimeout(400);
await page.click('a:has-text("Wokwi: 7-Segment Clock")');
await page.waitForURL("**/studio/**", { timeout: 15000 });
await page.waitForTimeout(5000);
await page.click('button[aria-label="Hide code panel"]').catch(()=>{});
await page.waitForTimeout(300);
await page.click('button[title="Fit to screen"]').catch(()=>{});
await page.waitForTimeout(500);
await page.screenshot({ path: "screenshots/39-lanes.png" });
console.log("captured lanes");
// validate flow
await page.click('button[aria-label="Show code panel"]').catch(()=>{});
await page.click('button:has-text("Description")');
await page.waitForTimeout(700);
await page.click('button:has-text("Validate with AI")');
await page.waitForTimeout(3000);
await page.screenshot({ path: "screenshots/40-validate.png" });
console.log("captured validate result");
await browser.close();
