import { chromium } from "playwright";
const BASE = "http://localhost:3000";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1600, height: 920 }, deviceScaleFactor: 1.25 });
const page = await ctx.newPage();
await page.goto(`${BASE}/login`, { waitUntil: "networkidle" });
await page.fill("#email", "tariro@springfield.robocode.africa");
await page.fill("#password", "password123");
await page.click('button:has-text("Sign in")');
await page.waitForURL("**/app", { timeout: 15000 });
await page.goto(`${BASE}/studio/new`, { waitUntil: "networkidle" });
await page.waitForTimeout(4500);
await page.click(".monaco-editor", { timeout: 8000 });
await page.keyboard.press("ControlOrMeta+A");
await page.keyboard.type("void setup() {\n  pinMode(13 OUTPUT);\n  Serial.begin(9600);\n}\nvoid loop() {}\n");
await page.waitForTimeout(1200);
await page.screenshot({ path: "screenshots/24-syntax-error.png" });
console.log("captured 24-syntax-error");
await browser.close();
