import { chromium } from "playwright";
const BASE = "http://localhost:3000";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1.25 });
const page = await ctx.newPage();
let pageError = null;
page.on("pageerror", (e) => (pageError = e.message));
await page.goto(`${BASE}/login`, { waitUntil: "networkidle" });
await page.fill("#email", "tariro@springfield.robocode.africa");
await page.fill("#password", "password123");
await page.click('button:has-text("Sign in")');
await page.waitForURL("**/app", { timeout: 15000 });
await page.goto(`${BASE}/app/learn/intro-robotics`, { waitUntil: "networkidle" });
await page.waitForTimeout(800);
const h1 = await page.locator("h1").first().textContent().catch(()=>null);
console.log("course page h1:", JSON.stringify(h1));
console.log("page error:", pageError || "NONE");
await page.screenshot({ path: "screenshots/28-course.png" });
await browser.close();
