import { chromium } from "playwright";
const BASE = "http://localhost:3000";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1500, height: 900 }, deviceScaleFactor: 1.25 });
const page = await ctx.newPage();
await page.goto(`${BASE}/login`, { waitUntil: "networkidle" });
await page.fill("#email", "tariro@springfield.robocode.africa");
await page.fill("#password", "password123");
await page.click('button:has-text("Sign in")');
await page.waitForURL("**/app", { timeout: 15000 });
await page.goto(`${BASE}/studio/new`, { waitUntil: "networkidle" });
await page.waitForTimeout(4000);
await page.click('button:has-text("Add component")');
await page.waitForTimeout(600);
await page.screenshot({ path: "screenshots/34-add-menu.png" });
console.log("captured add menu");
await page.keyboard.press("Escape");
await page.waitForTimeout(300);
await page.click('button[aria-label="More actions"]');
await page.waitForTimeout(500);
await page.screenshot({ path: "screenshots/35-overflow-menu.png" });
console.log("captured overflow menu");
await browser.close();
